//============================================================================
// KieeKey - A modified version based on OpenKey
//
// Original work:
//   OpenKey - Vietnamese input method engine
//   Copyright (C) 2019 Tuyen Mai - https://github.com/tuyenvm/OpenKey
//   Licensed under the GNU General Public License version 3.
//
// Modified work:
//   KieeKey v1.0.1 - refactored and completed logic
//   Copyright (C) 2026 coderunknow - https://github.com/coderunknow
//   SPDX-FileCopyrightText: 2026 coderunknow <https://github.com/coderunknow>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// File: src/core/FlatTables.hpp
// SPDX-License-Identifier: GPL-3.0-or-later
//============================================================================
//----------------------------------------------------------------------------
// KieeKey v1.0.1 — FlatTables.hpp (GENERATED by tools/gen_flat_tables.py)
//
// Compile-time flattened lookup tables: the same validated phonetics data as
// VietnameseTables.hpp, re-laid-out as constexpr flat storage so the hot path
// does O(1)/binary-search lookups with NO heap, NO std::map RB-tree walks and
// NO pointer chasing. Interface keeps the std::map/vector shape the engine
// already uses (find/end/begin/->second/[i]/size), so TextEngine.cpp compiles
// unchanged against these types. DO NOT EDIT BY HAND — regenerate instead.
//----------------------------------------------------------------------------
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace ok::text {

//---------------------------------------------------------------------------
// FlatVec<T> — (ptr,len) read-only view with std::vector-like access.
//---------------------------------------------------------------------------
template <class T>
struct FlatVec {
    const T* p = nullptr;
    std::size_t n = 0;
    constexpr FlatVec() noexcept = default;
    constexpr FlatVec(const T* pp, std::size_t nn) noexcept : p(pp), n(nn) {}
    [[nodiscard]] constexpr std::size_t size() const noexcept { return n; }
    [[nodiscard]] constexpr bool empty() const noexcept { return n == 0; }
    [[nodiscard]] constexpr const T& operator[](std::size_t i) const noexcept { return p[i]; }
    [[nodiscard]] constexpr const T* data() const noexcept { return p; }
    [[nodiscard]] constexpr const T* begin() const noexcept { return p; }
    [[nodiscard]] constexpr const T* end() const noexcept { return p + n; }
};

//---------------------------------------------------------------------------
// FlatMap<K,V,N> — sorted constexpr entries, binary-search find().
//---------------------------------------------------------------------------
template <class K, class V, std::size_t N>
struct FlatMap {
    struct Entry { K key; V second; };
    Entry entries[N]{};
    struct const_iterator {
        const Entry* e = nullptr;
        constexpr const_iterator() noexcept = default;
        constexpr explicit const_iterator(const Entry* p) noexcept : e(p) {}
        constexpr const_iterator& operator++() noexcept { ++e; return *this; }
        [[nodiscard]] constexpr bool operator==(const const_iterator& o) const noexcept { return e == o.e; }
        [[nodiscard]] constexpr bool operator!=(const const_iterator& o) const noexcept { return e != o.e; }
        [[nodiscard]] constexpr const Entry& operator*() const noexcept { return *e; }
        [[nodiscard]] constexpr const Entry* operator->() const noexcept { return e; }
    };
    [[nodiscard]] constexpr std::size_t size() const noexcept { return N; }
    [[nodiscard]] constexpr const_iterator begin() const noexcept { return const_iterator(entries); }
    [[nodiscard]] constexpr const_iterator end() const noexcept { return const_iterator(entries + N); }
    [[nodiscard]] constexpr const_iterator find(K k) const noexcept {
        const Entry* e = entries;
        std::size_t lo = 0, hi = N;
        while (lo < hi) {
            const std::size_t mid = (lo + hi) >> 1;
            if (e[mid].key < k) { lo = mid + 1; } else { hi = mid; }
        }
        if (lo < N && e[lo].key == k) { return const_iterator(e + lo); }
        return end();
    }
};

//---------------------------------------------------------------------------
// FlatCodeTable — code-table rows indexed O(1) by (char-'A')*3 + flagIdx.
//---------------------------------------------------------------------------
struct FlatCodeTable {
    std::array<std::uint16_t, 78> off;   // 0xFFFF = row absent
    std::array<std::uint8_t, 78> len;
    const std::uint16_t* data;
    struct Entry { std::uint32_t key; FlatVec<std::uint16_t> second; };
    struct const_iterator {
        Entry entry{};
        bool valid = false;
        constexpr const_iterator() noexcept = default;
        constexpr const_iterator(std::uint32_t k, std::size_t row, const FlatCodeTable* t, bool ok) noexcept
            : entry{k, ok ? FlatVec<std::uint16_t>{t->data + t->off[row], t->len[row]} : FlatVec<std::uint16_t>{}},
              valid(ok) {}
        [[nodiscard]] constexpr bool operator==(const const_iterator& o) const noexcept { return valid == o.valid; }
        [[nodiscard]] constexpr bool operator!=(const const_iterator& o) const noexcept { return valid != o.valid; }
        [[nodiscard]] constexpr const Entry& operator*() const noexcept { return entry; }
        [[nodiscard]] constexpr const Entry* operator->() const noexcept { return &entry; }
    };
    [[nodiscard]] constexpr const_iterator end() const noexcept { return const_iterator{}; }
    [[nodiscard]] constexpr const_iterator find(std::uint32_t key) const noexcept {
        const std::uint32_t c = key & 0xFFu;
        if (c < 0x41u || c > 0x5Au) { return end(); }
        const std::size_t idx = static_cast<std::size_t>(c - 0x41u) * 3 + ((key >> 17) & 7u);
        if (off[idx] == 0xFFFFu) { return end(); }
        return const_iterator(key, idx, this, true);
    }
};

//---------------------------------------------------------------------------
// Generated data (semantics identical to VietnameseTables.hpp)
//---------------------------------------------------------------------------
// ---- code tables ----------------------------------------------------
// kCodeTableUnicode: rows indexed by (char-'A')*3 + flag(0=plain,1=hat,2=w)
constexpr std::uint16_t kCodeTableUnicode_Data[] = { 0x00C2, 0x00E2, 0x0102, 0x0103, 0x00C1, 0x00E1, 0x00C0, 0x00E0, 0x1EA2, 0x1EA3, 0x00C3, 0x00E3, 0x1EA0, 0x1EA1, 0x1EA4, 0x1EA5, 0x1EA6, 0x1EA7, 0x1EA8, 0x1EA9, 0x1EAA, 0x1EAB, 0x1EAC, 0x1EAD, 0x1EAE, 0x1EAF, 0x1EB0, 0x1EB1, 0x1EB2, 0x1EB3, 0x1EB4, 0x1EB5, 0x1EB6, 0x1EB7, 0x0110, 0x0111, 0x00CA, 0x00EA, 0x0000, 0x0000, 0x00C9, 0x00E9, 0x00C8, 0x00E8, 0x1EBA, 0x1EBB, 0x1EBC, 0x1EBD, 0x1EB8, 0x1EB9, 0x1EBE, 0x1EBF, 0x1EC0, 0x1EC1, 0x1EC2, 0x1EC3, 0x1EC4, 0x1EC5, 0x1EC6, 0x1EC7, 0x00CD, 0x00ED, 0x00CC, 0x00EC, 0x1EC8, 0x1EC9, 0x128, 0x129, 0x1ECA, 0x1ECB, 0x00D4, 0x00F4, 0x01A0, 0x01A1, 0x00D3, 0x00F3, 0x00D2, 0x00F2, 0x1ECE, 0x1ECF, 0x00D5, 0x00F5, 0x1ECC, 0x1ECD, 0x1ED0, 0x1ED1, 0x1ED2, 0x1ED3, 0x1ED4, 0x1ED5, 0x1ED6, 0x1ED7, 0x1ED8, 0x1ED9, 0x1EDA, 0x1EDB, 0x1EDC, 0x1EDD, 0x1EDE, 0x1EDF, 0x1EE0, 0x1EE1, 0x1EE2, 0x1EE3, 0x0000, 0x0000, 0x01AF, 0x01B0, 0x00DA, 0x00FA, 0x00D9, 0x00F9, 0x1EE6, 0x1EE7, 0x0168, 0x0169, 0x1EE4, 0x1EE5, 0x1EE8, 0x1EE9, 0x1EEA, 0x1EEB, 0x1EEC, 0x1EED, 0x1EEE, 0x1EEF, 0x1EF0, 0x1EF1, 0x00DD, 0x00FD, 0x1EF2, 0x1EF3, 0x1EF6, 0x1EF7, 0x1EF8, 0x1EF9, 0x1EF4, 0x1EF5 };
constexpr std::array<std::uint16_t, 78> kCodeTableUnicode_Off = { 0, 14, 24, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 34, 0xFFFF, 0xFFFF, 36, 50, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 60, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 70, 84, 94, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 104, 0xFFFF, 118, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 128, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF };
constexpr std::array<std::uint8_t, 78> kCodeTableUnicode_Len = { 14, 10, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 14, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0 };
constexpr FlatCodeTable kCodeTableUnicode = { kCodeTableUnicode_Off, kCodeTableUnicode_Len, kCodeTableUnicode_Data };

// kCodeTableTcvn3: rows indexed by (char-'A')*3 + flag(0=plain,1=hat,2=w)
constexpr std::uint16_t kCodeTableTcvn3_Data[] = { 0xA2, 0xA9, 0xA1, 0xA8, 0xB8, 0xB8, 0xB5, 0xB5, 0xB6, 0xB6, 0xB7, 0xB7, 0xB9, 0xB9, 0xCA, 0xCA, 0xC7, 0xC7, 0xC8, 0xC8, 0xC9, 0xC9, 0xCB, 0xCB, 0xBE, 0xBE, 0xBB, 0xBB, 0xBC, 0xBC, 0xBD, 0xBD, 0xC6, 0xC6, 0xA7, 0xAE, 0xA3, 0xAA, 0x00, 0x00, 0xD0, 0xD0, 0xCC, 0xCC, 0xCE, 0xCE, 0xCF, 0xCF, 0xD1, 0xD1, 0xD5, 0xD5, 0xD2, 0xD2, 0xD3, 0xD3, 0xD4, 0xD4, 0xD6, 0xD6, 0xDD, 0xDD, 0xD7, 0xD7, 0xD8, 0xD8, 0xDc, 0xDc, 0xDe, 0xDe, 0xA4, 0xAB, 0xA5, 0xAC, 0xE3, 0xE3, 0xDF, 0xDF, 0xE1, 0xE1, 0xE2, 0xE2, 0xE4, 0xE4, 0xE8, 0xE8, 0xE5, 0xE5, 0xE6, 0xE6, 0xE7, 0xE7, 0xE9, 0xE9, 0xED, 0xED, 0xEA, 0xEA, 0xEB, 0xEB, 0xEC, 0xEC, 0xEE, 0xEE, 0x00, 0x00, 0xA6, 0xAD, 0xF3, 0xF3, 0xEF, 0xEF, 0xF1, 0xF1, 0xF2, 0xF2, 0xF4, 0xF4, 0xF8, 0xF8, 0xF5, 0xF5, 0xF6, 0xF6, 0xF7, 0xF7, 0xF9, 0xF9, 0xFD, 0xFD, 0xFA, 0xFA, 0xFB, 0xFB, 0xFC, 0xFC, 0xFE, 0xFE };
constexpr std::array<std::uint16_t, 78> kCodeTableTcvn3_Off = { 0, 14, 24, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 34, 0xFFFF, 0xFFFF, 36, 50, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 60, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 70, 84, 94, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 104, 0xFFFF, 118, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 128, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF };
constexpr std::array<std::uint8_t, 78> kCodeTableTcvn3_Len = { 14, 10, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 14, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0 };
constexpr FlatCodeTable kCodeTableTcvn3 = { kCodeTableTcvn3_Off, kCodeTableTcvn3_Len, kCodeTableTcvn3_Data };

// kCodeTableVniWindows: rows indexed by (char-'A')*3 + flag(0=plain,1=hat,2=w)
constexpr std::uint16_t kCodeTableVniWindows_Data[] = { 0xC241, 0xE261, 0xCA41, 0xEA61, 0xD941, 0xF961, 0xD841, 0xF861, 0xDB41, 0xFB61, 0xD541, 0xF561, 0xCF41, 0xEF61, 0xC141, 0xE161, 0xC041, 0xE061, 0xC541, 0xE561, 0xC341, 0xE361, 0xC441, 0xE461, 0xC941, 0xE961, 0xC841, 0xE861, 0xDA41, 0xFA61, 0xDC41, 0xFC61, 0xCB41, 0xEB61, 0x00D1, 0x00F1, 0xC245, 0xE265, 0x0000, 0x0000, 0xD945, 0xF965, 0xD845, 0xF865, 0xDB45, 0xFB65, 0xD545, 0xF565, 0xCF45, 0xEF65, 0xC145, 0xE165, 0xC045, 0xE065, 0xC545, 0xE565, 0xC345, 0xE365, 0xC445, 0xE465, 0x00CD, 0x00ED, 0x00CC, 0x00EC, 0x00C6, 0x00E6, 0x00D3, 0x00F3, 0x00D2, 0x00F2, 0xC24F, 0xE26F, 0x00D4, 0x00F4, 0xD94F, 0xF96F, 0xD84F, 0xF86F, 0xDB4F, 0xFB6F, 0xD54F, 0xF56F, 0xCF4F, 0xEF6F, 0xC14F, 0xE16F, 0xC04F, 0xE06F, 0xC54F, 0xE56F, 0xC34F, 0xE36F, 0xC44F, 0xE46F, 0xD9D4, 0xF9F4, 0xD8D4, 0xF8F4, 0xDBD4, 0xFBF4, 0xD5D4, 0xF5F4, 0xCFD4, 0xEFF4, 0x0000, 0x0000, 0x00D6, 0x00F6, 0xD955, 0xF975, 0xD855, 0xF875, 0xDB55, 0xFB75, 0xD555, 0xF575, 0xCF55, 0xEF75, 0xD9D6, 0xF9F6, 0xD8D6, 0xF8F6, 0xDBD6, 0xFBF6, 0xD5D6, 0xF5F6, 0xCFD6, 0xEFF6, 0xD959, 0xF979, 0xD859, 0xF879, 0xDB59, 0xFB79, 0xD559, 0xF579, 0x00CE, 0x00EE };
constexpr std::array<std::uint16_t, 78> kCodeTableVniWindows_Off = { 0, 14, 24, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 34, 0xFFFF, 0xFFFF, 36, 50, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 60, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 70, 84, 94, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 104, 0xFFFF, 118, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 128, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF };
constexpr std::array<std::uint8_t, 78> kCodeTableVniWindows_Len = { 14, 10, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 14, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0 };
constexpr FlatCodeTable kCodeTableVniWindows = { kCodeTableVniWindows_Off, kCodeTableVniWindows_Len, kCodeTableVniWindows_Data };

// kCodeTableUnicodeCompound: rows indexed by (char-'A')*3 + flag(0=plain,1=hat,2=w)
constexpr std::uint16_t kCodeTableUnicodeCompound_Data[] = { 0x00C2, 0x00E2, 0x0102, 0x0103, 0x2041, 0x2061, 0x4041, 0x4061, 0x6041, 0x6061, 0x8041, 0x8061, 0xA041, 0xA061, 0x20C2, 0x20E2, 0x40C2, 0x40E2, 0x60C2, 0x60E2, 0x80C2, 0x80E2, 0xA0C2, 0xA0E2, 0x2102, 0x2103, 0x4102, 0x4103, 0x6102, 0x6103, 0x8102, 0x8103, 0xA102, 0xA103, 0x0110, 0x0111, 0x00CA, 0x00EA, 0x0000, 0x0000, 0x2045, 0x2065, 0x4045, 0x4065, 0x6045, 0x6065, 0x8045, 0x8065, 0xA045, 0xA065, 0x20CA, 0x20EA, 0x40CA, 0x40EA, 0x60CA, 0x60EA, 0x80CA, 0x80EA, 0xA0CA, 0xA0EA, 0x2049, 0x2069, 0x4049, 0x4069, 0x6049, 0x6069, 0x8049, 0x8069, 0xA049, 0xA069, 0x00D4, 0x00F4, 0x01A0, 0x01A1, 0x204F, 0x206F, 0x404F, 0x406F, 0x604F, 0x606F, 0x804F, 0x806F, 0xA04F, 0xA06F, 0x20D4, 0x20F4, 0x40D4, 0x40F4, 0x60D4, 0x60F4, 0x80D4, 0x80F4, 0xA0D4, 0xA0F4, 0x21A0, 0x21A1, 0x41A0, 0x41A1, 0x61A0, 0x61A1, 0x81A0, 0x81A1, 0xA1A0, 0xA1A1, 0x0000, 0x0000, 0x01AF, 0x01B0, 0x2055, 0x2075, 0x4055, 0x4075, 0x6055, 0x6075, 0x8055, 0x8075, 0xA055, 0xA075, 0x21AF, 0x21B0, 0x41AF, 0x41B0, 0x61AF, 0x61B0, 0x81AF, 0x81B0, 0xA1AF, 0xA1B0, 0x2059, 0x2079, 0x4059, 0x4079, 0x6059, 0x6079, 0x8059, 0x8079, 0xA059, 0xA079 };
constexpr std::array<std::uint16_t, 78> kCodeTableUnicodeCompound_Off = { 0, 14, 24, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 34, 0xFFFF, 0xFFFF, 36, 50, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 60, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 70, 84, 94, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 104, 0xFFFF, 118, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 128, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF };
constexpr std::array<std::uint8_t, 78> kCodeTableUnicodeCompound_Len = { 14, 10, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 14, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0 };
constexpr FlatCodeTable kCodeTableUnicodeCompound = { kCodeTableUnicodeCompound_Off, kCodeTableUnicodeCompound_Len, kCodeTableUnicodeCompound_Data };

// kCodeTableCp1258: rows indexed by (char-'A')*3 + flag(0=plain,1=hat,2=w)
constexpr std::uint16_t kCodeTableCp1258_Data[] = { 0x00C2, 0x00E2, 0x00C3, 0x00E3, 0xEC41, 0xEC61, 0xCC41, 0xCC61, 0xD241, 0xD261, 0xDE41, 0xDE61, 0xF241, 0xF261, 0xECC2, 0xECE2, 0xCCC2, 0xCCE2, 0xD2C2, 0xD2E2, 0xDEC2, 0xDEE2, 0xF2C2, 0xF2E2, 0xECC3, 0xECE3, 0xCCC3, 0xCCE3, 0xD2C3, 0xD2E3, 0xDEC3, 0xDEE3, 0xF2C3, 0xF2E3, 0x00D0, 0x00F0, 0x00CA, 0x00EA, 0x0000, 0x0000, 0xEC45, 0xEC65, 0xCC45, 0xCC65, 0xD245, 0xD265, 0xDE45, 0xDE65, 0xF245, 0xF265, 0xECCA, 0xECEA, 0xCCCA, 0xCCEA, 0xD2CA, 0xD2EA, 0xDECA, 0xDEEA, 0xF2CA, 0xF2EA, 0xEC49, 0xEC69, 0xCC49, 0xCC69, 0xD249, 0xD269, 0xDE49, 0xDE69, 0xF249, 0xF269, 0x00D4, 0x00F4, 0x00D5, 0x00F5, 0xEC4F, 0xEC6F, 0xCC4F, 0xCC6F, 0xD24F, 0xD26F, 0xDE4F, 0xDE6F, 0xF24F, 0xF26F, 0xECD4, 0xECF4, 0xCCD4, 0xCCF4, 0xD2D4, 0xD2F4, 0xDED4, 0xDEF4, 0xF2D4, 0xF2F4, 0xECD5, 0xECF5, 0xCCD5, 0xCCF5, 0xD2D5, 0xD2F5, 0xDED5, 0xDEF5, 0xF2D5, 0xF2F5, 0x0000, 0x0000, 0x00DD, 0x00FD, 0xEC55, 0xEC75, 0xCC55, 0xCC75, 0xD255, 0xD275, 0xDE55, 0xDE75, 0xF255, 0xF275, 0xECDD, 0xECFD, 0xCCDD, 0xCCFD, 0xD2DD, 0xD2FD, 0xDEDD, 0xDEFD, 0xF2DD, 0xF2FD, 0xEC59, 0xEC79, 0xCC59, 0xCC79, 0xD259, 0xD279, 0xDE59, 0xDE79, 0xF259, 0xF279 };
constexpr std::array<std::uint16_t, 78> kCodeTableCp1258_Off = { 0, 14, 24, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 34, 0xFFFF, 0xFFFF, 36, 50, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 60, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 70, 84, 94, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 104, 0xFFFF, 118, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 128, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF };
constexpr std::array<std::uint8_t, 78> kCodeTableCp1258_Len = { 14, 10, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 14, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0 };
constexpr FlatCodeTable kCodeTableCp1258 = { kCodeTableCp1258_Off, kCodeTableCp1258_Len, kCodeTableCp1258_Data };

// ---- vowel structural maps ------------------------------------------
// kVowel: 4 keys, 66 sequences
constexpr std::uint16_t kVowel_Inner_Data[] = { 0x41, 0x4E, 0x47, 0x41, 0x47|kEndConsonantMask, 0x41, 0x4E, 0x41, 0x4D, 0x41, 0x55, 0x41, 0x59, 0x41, 0x54, 0x41, 0x50, 0x41, 0x41, 0x43, 0x45, 0x4E, 0x48, 0x45, 0x48|kEndConsonantMask, 0x45, 0x4E, 0x47, 0x45, 0x47|kEndConsonantMask, 0x45, 0x43, 0x48, 0x45, 0x4B|kEndConsonantMask, 0x45, 0x43, 0x45, 0x54, 0x45, 0x59, 0x45, 0x55, 0x45, 0x50, 0x45, 0x43, 0x45, 0x4E, 0x45, 0x4D, 0x45, 0x4F, 0x4E, 0x47, 0x4F, 0x47|kEndConsonantMask, 0x4F, 0x4E, 0x4F, 0x4D, 0x4F, 0x49, 0x4F, 0x43, 0x4F, 0x54, 0x4F, 0x50, 0x4F, 0x4F, 0x4E, 0x55, 0x4F, 0x4E, 0x47, 0x55, 0x4F, 0x47|kEndConsonantMask, 0x55, 0x4F, 0x4E, 0x55, 0x4F, 0x49, 0x55, 0x4F, 0x43, 0x4F, 0x49, 0x4F, 0x50, 0x4F, 0x4D, 0x4F, 0x41, 0x4F, 0x54, 0x55, 0x4E, 0x47, 0x55, 0x47|kEndConsonantMask, 0x41, 0x4E, 0x47, 0x41, 0x47|kEndConsonantMask, 0x55, 0x4E, 0x55, 0x4D, 0x55, 0x43, 0x55, 0x41, 0x55, 0x49, 0x55, 0x54, 0x55, 0x41, 0x50, 0x41, 0x54, 0x41, 0x4D, 0x41, 0x4E, 0x41, 0x41, 0x43, 0x41, 0x43, 0x48, 0x41, 0x4B|kEndConsonantMask, 0x4F, 0x55, 0x55 };
constexpr FlatVec<std::uint16_t> kVowel_Inner[] = {
    {&kVowel_Inner_Data[0], 3},
    {&kVowel_Inner_Data[3], 2},
    {&kVowel_Inner_Data[5], 2},
    {&kVowel_Inner_Data[7], 2},
    {&kVowel_Inner_Data[9], 2},
    {&kVowel_Inner_Data[11], 2},
    {&kVowel_Inner_Data[13], 2},
    {&kVowel_Inner_Data[15], 2},
    {&kVowel_Inner_Data[17], 1},
    {&kVowel_Inner_Data[18], 2},
    {&kVowel_Inner_Data[20], 3},
    {&kVowel_Inner_Data[23], 2},
    {&kVowel_Inner_Data[25], 3},
    {&kVowel_Inner_Data[28], 2},
    {&kVowel_Inner_Data[30], 3},
    {&kVowel_Inner_Data[33], 2},
    {&kVowel_Inner_Data[35], 2},
    {&kVowel_Inner_Data[37], 2},
    {&kVowel_Inner_Data[39], 2},
    {&kVowel_Inner_Data[41], 2},
    {&kVowel_Inner_Data[43], 2},
    {&kVowel_Inner_Data[45], 2},
    {&kVowel_Inner_Data[47], 2},
    {&kVowel_Inner_Data[49], 2},
    {&kVowel_Inner_Data[51], 1},
    {&kVowel_Inner_Data[52], 3},
    {&kVowel_Inner_Data[55], 2},
    {&kVowel_Inner_Data[57], 2},
    {&kVowel_Inner_Data[59], 2},
    {&kVowel_Inner_Data[61], 2},
    {&kVowel_Inner_Data[63], 2},
    {&kVowel_Inner_Data[65], 2},
    {&kVowel_Inner_Data[67], 2},
    {&kVowel_Inner_Data[69], 1},
    {&kVowel_Inner_Data[70], 2},
    {&kVowel_Inner_Data[72], 4},
    {&kVowel_Inner_Data[76], 3},
    {&kVowel_Inner_Data[79], 3},
    {&kVowel_Inner_Data[82], 3},
    {&kVowel_Inner_Data[85], 3},
    {&kVowel_Inner_Data[88], 2},
    {&kVowel_Inner_Data[90], 2},
    {&kVowel_Inner_Data[92], 2},
    {&kVowel_Inner_Data[94], 2},
    {&kVowel_Inner_Data[96], 2},
    {&kVowel_Inner_Data[98], 3},
    {&kVowel_Inner_Data[101], 2},
    {&kVowel_Inner_Data[103], 3},
    {&kVowel_Inner_Data[106], 2},
    {&kVowel_Inner_Data[108], 2},
    {&kVowel_Inner_Data[110], 2},
    {&kVowel_Inner_Data[112], 2},
    {&kVowel_Inner_Data[114], 2},
    {&kVowel_Inner_Data[116], 2},
    {&kVowel_Inner_Data[118], 2},
    {&kVowel_Inner_Data[120], 1},
    {&kVowel_Inner_Data[121], 2},
    {&kVowel_Inner_Data[123], 2},
    {&kVowel_Inner_Data[125], 2},
    {&kVowel_Inner_Data[127], 2},
    {&kVowel_Inner_Data[129], 1},
    {&kVowel_Inner_Data[130], 2},
    {&kVowel_Inner_Data[132], 3},
    {&kVowel_Inner_Data[135], 2},
    {&kVowel_Inner_Data[137], 1},
    {&kVowel_Inner_Data[138], 2}
};
constexpr FlatMap<std::uint16_t, FlatVec<FlatVec<std::uint16_t>>, 4> kVowel = {
    { { 0x41, { &kVowel_Inner[0], 10 } },
    { 0x45, { &kVowel_Inner[10], 15 } },
    { 0x4F, { &kVowel_Inner[25], 9 } },
    { 0x57, { &kVowel_Inner[34], 32 } } }
};

// kVowelCombine: 6 keys, 47 sequences
constexpr std::uint32_t kVowelCombine_Inner_Data[] = { 0, 0x41, 0x49, 0, 0x41, 0x4F, 0, 0x41, 0x55, 0, 0x41|kToneMask, 0x55, 0, 0x41, 0x59, 0, 0x41|kToneMask, 0x59, 0, 0x45, 0x4F, 0, 0x45|kToneMask, 0x55, 1, 0x49, 0x45|kToneMask, 0x55, 0, 0x49, 0x41, 1, 0x49, 0x45|kToneMask, 0, 0x49, 0x55, 0, 0x4F, 0x41, 0x49, 0, 0x4F, 0x41, 0x4F, 0, 0x4F, 0x41, 0x59, 0, 0x4F, 0x45, 0x4F, 1, 0x4F, 0x41, 1, 0x4F, 0x41|kToneWMask, 1, 0x4F, 0x45, 0, 0x4F, 0x49, 0, 0x4F|kToneMask, 0x49, 0, 0x4F|kToneWMask, 0x49, 1, 0x4F, 0x4F, 1, 0x4F|kToneMask, 0x4F|kToneMask, 0, 0x55, 0x59, 0x55, 1, 0x55, 0x59, 0x45|kToneMask, 0, 0x55, 0x59, 0x41, 0, 0x55|kToneWMask, 0x4F|kToneWMask, 0x55, 0, 0x55|kToneWMask, 0x4F|kToneWMask, 0x49, 0, 0x55, 0x4F|kToneMask, 0x49, 0, 0x55, 0x41|kToneMask, 0x59, 1, 0x55, 0x41, 0x4F, 1, 0x55, 0x41, 1, 0x55, 0x41|kToneWMask, 1, 0x55, 0x41|kToneMask, 0, 0x55|kToneWMask, 0x41, 1, 0x55, 0x45|kToneMask, 0, 0x55, 0x49, 0, 0x55|kToneWMask, 0x49, 1, 0x55, 0x4F, 1, 0x55, 0x4F|kToneMask, 0, 0x55, 0x4F|kToneWMask, 1, 0x55|kToneWMask, 0x4F|kToneWMask, 0, 0x55|kToneWMask, 0x55, 1, 0x55, 0x59, 0, 0x59, 0x45|kToneMask, 0x55, 1, 0x59, 0x45|kToneMask };
constexpr FlatVec<std::uint32_t> kVowelCombine_Inner[] = {
    {&kVowelCombine_Inner_Data[0], 3},
    {&kVowelCombine_Inner_Data[3], 3},
    {&kVowelCombine_Inner_Data[6], 3},
    {&kVowelCombine_Inner_Data[9], 3},
    {&kVowelCombine_Inner_Data[12], 3},
    {&kVowelCombine_Inner_Data[15], 3},
    {&kVowelCombine_Inner_Data[18], 3},
    {&kVowelCombine_Inner_Data[21], 3},
    {&kVowelCombine_Inner_Data[24], 4},
    {&kVowelCombine_Inner_Data[28], 3},
    {&kVowelCombine_Inner_Data[31], 3},
    {&kVowelCombine_Inner_Data[34], 3},
    {&kVowelCombine_Inner_Data[37], 4},
    {&kVowelCombine_Inner_Data[41], 4},
    {&kVowelCombine_Inner_Data[45], 4},
    {&kVowelCombine_Inner_Data[49], 4},
    {&kVowelCombine_Inner_Data[53], 3},
    {&kVowelCombine_Inner_Data[56], 3},
    {&kVowelCombine_Inner_Data[59], 3},
    {&kVowelCombine_Inner_Data[62], 3},
    {&kVowelCombine_Inner_Data[65], 3},
    {&kVowelCombine_Inner_Data[68], 3},
    {&kVowelCombine_Inner_Data[71], 3},
    {&kVowelCombine_Inner_Data[74], 3},
    {&kVowelCombine_Inner_Data[77], 4},
    {&kVowelCombine_Inner_Data[81], 4},
    {&kVowelCombine_Inner_Data[85], 4},
    {&kVowelCombine_Inner_Data[89], 4},
    {&kVowelCombine_Inner_Data[93], 4},
    {&kVowelCombine_Inner_Data[97], 4},
    {&kVowelCombine_Inner_Data[101], 4},
    {&kVowelCombine_Inner_Data[105], 4},
    {&kVowelCombine_Inner_Data[109], 3},
    {&kVowelCombine_Inner_Data[112], 3},
    {&kVowelCombine_Inner_Data[115], 3},
    {&kVowelCombine_Inner_Data[118], 3},
    {&kVowelCombine_Inner_Data[121], 3},
    {&kVowelCombine_Inner_Data[124], 3},
    {&kVowelCombine_Inner_Data[127], 3},
    {&kVowelCombine_Inner_Data[130], 3},
    {&kVowelCombine_Inner_Data[133], 3},
    {&kVowelCombine_Inner_Data[136], 3},
    {&kVowelCombine_Inner_Data[139], 3},
    {&kVowelCombine_Inner_Data[142], 3},
    {&kVowelCombine_Inner_Data[145], 3},
    {&kVowelCombine_Inner_Data[148], 4},
    {&kVowelCombine_Inner_Data[152], 3}
};
constexpr FlatMap<std::uint16_t, FlatVec<FlatVec<std::uint32_t>>, 6> kVowelCombine = {
    { { 0x41, { &kVowelCombine_Inner[0], 6 } },
    { 0x45, { &kVowelCombine_Inner[6], 2 } },
    { 0x49, { &kVowelCombine_Inner[8], 4 } },
    { 0x4F, { &kVowelCombine_Inner[12], 12 } },
    { 0x55, { &kVowelCombine_Inner[24], 21 } },
    { 0x59, { &kVowelCombine_Inner[45], 2 } } }
};

// kVowelForMark: 6 keys, 79 sequences
constexpr std::uint16_t kVowelForMark_Inner_Data[] = { 0x41, 0x4E, 0x47, 0x41, 0x47|kEndConsonantMask, 0x41, 0x4E, 0x41, 0x4E, 0x48, 0x41, 0x48|kEndConsonantMask, 0x41, 0x4D, 0x41, 0x55, 0x41, 0x59, 0x41, 0x54, 0x41, 0x50, 0x41, 0x41, 0x43, 0x41, 0x49, 0x41, 0x4F, 0x41, 0x43, 0x48, 0x41, 0x4B|kEndConsonantMask, 0x45, 0x4E, 0x48, 0x45, 0x48|kEndConsonantMask, 0x45, 0x4E, 0x47, 0x45, 0x47|kEndConsonantMask, 0x45, 0x43, 0x48, 0x45, 0x4B|kEndConsonantMask, 0x45, 0x43, 0x45, 0x54, 0x45, 0x59, 0x45, 0x55, 0x45, 0x50, 0x45, 0x43, 0x45, 0x4E, 0x45, 0x4D, 0x45, 0x49, 0x4E, 0x48, 0x49, 0x48|kEndConsonantMask, 0x49, 0x43, 0x48, 0x49, 0x4B|kEndConsonantMask, 0x49, 0x4E, 0x49, 0x54, 0x49, 0x55, 0x49, 0x55, 0x50, 0x49, 0x4E, 0x49, 0x4D, 0x49, 0x50, 0x49, 0x41, 0x49, 0x43, 0x49, 0x4F, 0x4F, 0x4E, 0x47, 0x4F, 0x4F, 0x47|kEndConsonantMask, 0x4F, 0x4E, 0x47, 0x4F, 0x47|kEndConsonantMask, 0x4F, 0x4F, 0x4E, 0x4F, 0x4F, 0x43, 0x4F, 0x4F, 0x4F, 0x4E, 0x4F, 0x4D, 0x4F, 0x49, 0x4F, 0x43, 0x4F, 0x54, 0x4F, 0x50, 0x4F, 0x55, 0x4E, 0x47, 0x55, 0x47|kEndConsonantMask, 0x55, 0x49, 0x55, 0x4F, 0x55, 0x59, 0x55, 0x59, 0x4E, 0x55, 0x59, 0x54, 0x55, 0x59, 0x50, 0x55, 0x59, 0x4E, 0x48, 0x55, 0x59, 0x48|kEndConsonantMask, 0x55, 0x54, 0x55, 0x55, 0x55, 0x41, 0x55, 0x49, 0x55, 0x43, 0x55, 0x4E, 0x55, 0x4D, 0x55, 0x50, 0x55, 0x59 };
constexpr FlatVec<std::uint16_t> kVowelForMark_Inner[] = {
    {&kVowelForMark_Inner_Data[0], 3},
    {&kVowelForMark_Inner_Data[3], 2},
    {&kVowelForMark_Inner_Data[5], 2},
    {&kVowelForMark_Inner_Data[7], 3},
    {&kVowelForMark_Inner_Data[10], 2},
    {&kVowelForMark_Inner_Data[12], 2},
    {&kVowelForMark_Inner_Data[14], 2},
    {&kVowelForMark_Inner_Data[16], 2},
    {&kVowelForMark_Inner_Data[18], 2},
    {&kVowelForMark_Inner_Data[20], 2},
    {&kVowelForMark_Inner_Data[22], 1},
    {&kVowelForMark_Inner_Data[23], 2},
    {&kVowelForMark_Inner_Data[25], 2},
    {&kVowelForMark_Inner_Data[27], 2},
    {&kVowelForMark_Inner_Data[29], 3},
    {&kVowelForMark_Inner_Data[32], 2},
    {&kVowelForMark_Inner_Data[34], 3},
    {&kVowelForMark_Inner_Data[37], 2},
    {&kVowelForMark_Inner_Data[39], 3},
    {&kVowelForMark_Inner_Data[42], 2},
    {&kVowelForMark_Inner_Data[44], 3},
    {&kVowelForMark_Inner_Data[47], 2},
    {&kVowelForMark_Inner_Data[49], 2},
    {&kVowelForMark_Inner_Data[51], 2},
    {&kVowelForMark_Inner_Data[53], 2},
    {&kVowelForMark_Inner_Data[55], 2},
    {&kVowelForMark_Inner_Data[57], 2},
    {&kVowelForMark_Inner_Data[59], 2},
    {&kVowelForMark_Inner_Data[61], 2},
    {&kVowelForMark_Inner_Data[63], 2},
    {&kVowelForMark_Inner_Data[65], 1},
    {&kVowelForMark_Inner_Data[66], 3},
    {&kVowelForMark_Inner_Data[69], 2},
    {&kVowelForMark_Inner_Data[71], 3},
    {&kVowelForMark_Inner_Data[74], 2},
    {&kVowelForMark_Inner_Data[76], 2},
    {&kVowelForMark_Inner_Data[78], 2},
    {&kVowelForMark_Inner_Data[80], 2},
    {&kVowelForMark_Inner_Data[82], 3},
    {&kVowelForMark_Inner_Data[85], 2},
    {&kVowelForMark_Inner_Data[87], 2},
    {&kVowelForMark_Inner_Data[89], 2},
    {&kVowelForMark_Inner_Data[91], 2},
    {&kVowelForMark_Inner_Data[93], 2},
    {&kVowelForMark_Inner_Data[95], 1},
    {&kVowelForMark_Inner_Data[96], 4},
    {&kVowelForMark_Inner_Data[100], 3},
    {&kVowelForMark_Inner_Data[103], 3},
    {&kVowelForMark_Inner_Data[106], 2},
    {&kVowelForMark_Inner_Data[108], 3},
    {&kVowelForMark_Inner_Data[111], 3},
    {&kVowelForMark_Inner_Data[114], 2},
    {&kVowelForMark_Inner_Data[116], 2},
    {&kVowelForMark_Inner_Data[118], 2},
    {&kVowelForMark_Inner_Data[120], 2},
    {&kVowelForMark_Inner_Data[122], 2},
    {&kVowelForMark_Inner_Data[124], 2},
    {&kVowelForMark_Inner_Data[126], 2},
    {&kVowelForMark_Inner_Data[128], 1},
    {&kVowelForMark_Inner_Data[129], 3},
    {&kVowelForMark_Inner_Data[132], 2},
    {&kVowelForMark_Inner_Data[134], 2},
    {&kVowelForMark_Inner_Data[136], 2},
    {&kVowelForMark_Inner_Data[138], 2},
    {&kVowelForMark_Inner_Data[140], 3},
    {&kVowelForMark_Inner_Data[143], 3},
    {&kVowelForMark_Inner_Data[146], 3},
    {&kVowelForMark_Inner_Data[149], 4},
    {&kVowelForMark_Inner_Data[153], 3},
    {&kVowelForMark_Inner_Data[156], 2},
    {&kVowelForMark_Inner_Data[158], 2},
    {&kVowelForMark_Inner_Data[160], 2},
    {&kVowelForMark_Inner_Data[162], 2},
    {&kVowelForMark_Inner_Data[164], 2},
    {&kVowelForMark_Inner_Data[166], 2},
    {&kVowelForMark_Inner_Data[168], 2},
    {&kVowelForMark_Inner_Data[170], 2},
    {&kVowelForMark_Inner_Data[172], 1},
    {&kVowelForMark_Inner_Data[173], 1}
};
constexpr FlatMap<std::uint16_t, FlatVec<FlatVec<std::uint16_t>>, 6> kVowelForMark = {
    { { 0x41, { &kVowelForMark_Inner[0], 16 } },
    { 0x45, { &kVowelForMark_Inner[16], 15 } },
    { 0x49, { &kVowelForMark_Inner[31], 14 } },
    { 0x4F, { &kVowelForMark_Inner[45], 14 } },
    { 0x55, { &kVowelForMark_Inner[59], 19 } },
    { 0x59, { &kVowelForMark_Inner[78], 1 } } }
};

// ---- plain structural tables ----------------------------------------
constexpr std::uint16_t kConsonantD_Inner_Data[] = { 0x44, 0x45, 0x4E, 0x48, 0x44, 0x45, 0x48|kEndConsonantMask, 0x44, 0x45, 0x4E, 0x47, 0x44, 0x45, 0x47|kEndConsonantMask, 0x44, 0x45, 0x43, 0x48, 0x44, 0x45, 0x4B|kEndConsonantMask, 0x44, 0x45, 0x4E, 0x44, 0x45, 0x43, 0x44, 0x45, 0x4D, 0x44, 0x45, 0x44, 0x45, 0x54, 0x44, 0x45, 0x55, 0x44, 0x45, 0x4F, 0x44, 0x45, 0x50, 0x44, 0x55, 0x4E, 0x47, 0x44, 0x55, 0x47|kEndConsonantMask, 0x44, 0x55, 0x4E, 0x44, 0x55, 0x4D, 0x44, 0x55, 0x43, 0x44, 0x55, 0x4F, 0x44, 0x55, 0x41, 0x44, 0x55, 0x4F, 0x49, 0x44, 0x55, 0x4F, 0x43, 0x44, 0x55, 0x4F, 0x4E, 0x44, 0x55, 0x4F, 0x4E, 0x47, 0x44, 0x55, 0x4F, 0x47|kEndConsonantMask, 0x44, 0x55, 0x44, 0x55, 0x50, 0x44, 0x55, 0x54, 0x44, 0x55, 0x49, 0x44, 0x49, 0x43, 0x48, 0x44, 0x49, 0x4B|kEndConsonantMask, 0x44, 0x49, 0x43, 0x44, 0x49, 0x4E, 0x48, 0x44, 0x49, 0x48|kEndConsonantMask, 0x44, 0x49, 0x4E, 0x44, 0x49, 0x44, 0x49, 0x41, 0x44, 0x49, 0x45, 0x44, 0x49, 0x45, 0x43, 0x44, 0x49, 0x45, 0x55, 0x44, 0x49, 0x45, 0x4E, 0x44, 0x49, 0x45, 0x4D, 0x44, 0x49, 0x45, 0x50, 0x44, 0x49, 0x54, 0x44, 0x4F, 0x44, 0x4F, 0x41, 0x44, 0x4F, 0x41, 0x4E, 0x44, 0x4F, 0x41, 0x4E, 0x47, 0x44, 0x4F, 0x41, 0x47|kEndConsonantMask, 0x44, 0x4F, 0x41, 0x4E, 0x48, 0x44, 0x4F, 0x41, 0x48|kEndConsonantMask, 0x44, 0x4F, 0x41, 0x4D, 0x44, 0x4F, 0x45, 0x44, 0x4F, 0x49, 0x44, 0x4F, 0x50, 0x44, 0x4F, 0x43, 0x44, 0x4F, 0x4E, 0x44, 0x4F, 0x4E, 0x47, 0x44, 0x4F, 0x47|kEndConsonantMask, 0x44, 0x4F, 0x4D, 0x44, 0x4F, 0x54, 0x44, 0x41, 0x44, 0x41, 0x54, 0x44, 0x41, 0x59, 0x44, 0x41, 0x55, 0x44, 0x41, 0x49, 0x44, 0x41, 0x4F, 0x44, 0x41, 0x50, 0x44, 0x41, 0x43, 0x44, 0x41, 0x43, 0x48, 0x44, 0x41, 0x4B|kEndConsonantMask, 0x44, 0x41, 0x4E, 0x44, 0x41, 0x4E, 0x48, 0x44, 0x41, 0x48|kEndConsonantMask, 0x44, 0x41, 0x4E, 0x47, 0x44, 0x41, 0x47|kEndConsonantMask, 0x44, 0x41, 0x4D, 0x44 };
constexpr FlatVec<std::uint16_t> kConsonantD_Inner[] = {
    {&kConsonantD_Inner_Data[0], 4},
    {&kConsonantD_Inner_Data[4], 3},
    {&kConsonantD_Inner_Data[7], 4},
    {&kConsonantD_Inner_Data[11], 3},
    {&kConsonantD_Inner_Data[14], 4},
    {&kConsonantD_Inner_Data[18], 3},
    {&kConsonantD_Inner_Data[21], 3},
    {&kConsonantD_Inner_Data[24], 3},
    {&kConsonantD_Inner_Data[27], 3},
    {&kConsonantD_Inner_Data[30], 2},
    {&kConsonantD_Inner_Data[32], 3},
    {&kConsonantD_Inner_Data[35], 3},
    {&kConsonantD_Inner_Data[38], 3},
    {&kConsonantD_Inner_Data[41], 3},
    {&kConsonantD_Inner_Data[44], 4},
    {&kConsonantD_Inner_Data[48], 3},
    {&kConsonantD_Inner_Data[51], 3},
    {&kConsonantD_Inner_Data[54], 3},
    {&kConsonantD_Inner_Data[57], 3},
    {&kConsonantD_Inner_Data[60], 3},
    {&kConsonantD_Inner_Data[63], 3},
    {&kConsonantD_Inner_Data[66], 4},
    {&kConsonantD_Inner_Data[70], 4},
    {&kConsonantD_Inner_Data[74], 4},
    {&kConsonantD_Inner_Data[78], 5},
    {&kConsonantD_Inner_Data[83], 4},
    {&kConsonantD_Inner_Data[87], 2},
    {&kConsonantD_Inner_Data[89], 3},
    {&kConsonantD_Inner_Data[92], 3},
    {&kConsonantD_Inner_Data[95], 3},
    {&kConsonantD_Inner_Data[98], 4},
    {&kConsonantD_Inner_Data[102], 3},
    {&kConsonantD_Inner_Data[105], 3},
    {&kConsonantD_Inner_Data[108], 4},
    {&kConsonantD_Inner_Data[112], 3},
    {&kConsonantD_Inner_Data[115], 3},
    {&kConsonantD_Inner_Data[118], 2},
    {&kConsonantD_Inner_Data[120], 3},
    {&kConsonantD_Inner_Data[123], 3},
    {&kConsonantD_Inner_Data[126], 4},
    {&kConsonantD_Inner_Data[130], 4},
    {&kConsonantD_Inner_Data[134], 4},
    {&kConsonantD_Inner_Data[138], 4},
    {&kConsonantD_Inner_Data[142], 4},
    {&kConsonantD_Inner_Data[146], 3},
    {&kConsonantD_Inner_Data[149], 2},
    {&kConsonantD_Inner_Data[151], 3},
    {&kConsonantD_Inner_Data[154], 4},
    {&kConsonantD_Inner_Data[158], 5},
    {&kConsonantD_Inner_Data[163], 4},
    {&kConsonantD_Inner_Data[167], 5},
    {&kConsonantD_Inner_Data[172], 4},
    {&kConsonantD_Inner_Data[176], 4},
    {&kConsonantD_Inner_Data[180], 3},
    {&kConsonantD_Inner_Data[183], 3},
    {&kConsonantD_Inner_Data[186], 3},
    {&kConsonantD_Inner_Data[189], 3},
    {&kConsonantD_Inner_Data[192], 3},
    {&kConsonantD_Inner_Data[195], 4},
    {&kConsonantD_Inner_Data[199], 3},
    {&kConsonantD_Inner_Data[202], 3},
    {&kConsonantD_Inner_Data[205], 3},
    {&kConsonantD_Inner_Data[208], 2},
    {&kConsonantD_Inner_Data[210], 3},
    {&kConsonantD_Inner_Data[213], 3},
    {&kConsonantD_Inner_Data[216], 3},
    {&kConsonantD_Inner_Data[219], 3},
    {&kConsonantD_Inner_Data[222], 3},
    {&kConsonantD_Inner_Data[225], 3},
    {&kConsonantD_Inner_Data[228], 3},
    {&kConsonantD_Inner_Data[231], 4},
    {&kConsonantD_Inner_Data[235], 3},
    {&kConsonantD_Inner_Data[238], 3},
    {&kConsonantD_Inner_Data[241], 4},
    {&kConsonantD_Inner_Data[245], 3},
    {&kConsonantD_Inner_Data[248], 4},
    {&kConsonantD_Inner_Data[252], 3},
    {&kConsonantD_Inner_Data[255], 3},
    {&kConsonantD_Inner_Data[258], 1}
};
constexpr FlatVec<FlatVec<std::uint16_t>> kConsonantD = { &kConsonantD_Inner[0], 79 };

constexpr std::uint16_t kConsonantTable_Inner_Data[] = { 0x4E, 0x47, 0x48, 0x50, 0x48, 0x54, 0x48, 0x54, 0x52, 0x47, 0x49, 0x43, 0x48, 0x4E, 0x48, 0x4E, 0x47, 0x4B, 0x48, 0x47, 0x48, 0x47, 0x43, 0x51, 0x4B, 0x54, 0x52, 0x48, 0x42, 0x4D, 0x56, 0x4E, 0x4C, 0x58, 0x50, 0x53, 0x44, 0x46|kConsonantAllowMask, 0x57|kConsonantAllowMask, 0x5A|kConsonantAllowMask, 0x4A|kConsonantAllowMask, 0x46|kEndConsonantMask, 0x57|kEndConsonantMask, 0x4A|kEndConsonantMask };
constexpr FlatVec<std::uint16_t> kConsonantTable_Inner[] = {
    {&kConsonantTable_Inner_Data[0], 3},
    {&kConsonantTable_Inner_Data[3], 2},
    {&kConsonantTable_Inner_Data[5], 2},
    {&kConsonantTable_Inner_Data[7], 2},
    {&kConsonantTable_Inner_Data[9], 2},
    {&kConsonantTable_Inner_Data[11], 2},
    {&kConsonantTable_Inner_Data[13], 2},
    {&kConsonantTable_Inner_Data[15], 2},
    {&kConsonantTable_Inner_Data[17], 2},
    {&kConsonantTable_Inner_Data[19], 2},
    {&kConsonantTable_Inner_Data[21], 1},
    {&kConsonantTable_Inner_Data[22], 1},
    {&kConsonantTable_Inner_Data[23], 1},
    {&kConsonantTable_Inner_Data[24], 1},
    {&kConsonantTable_Inner_Data[25], 1},
    {&kConsonantTable_Inner_Data[26], 1},
    {&kConsonantTable_Inner_Data[27], 1},
    {&kConsonantTable_Inner_Data[28], 1},
    {&kConsonantTable_Inner_Data[29], 1},
    {&kConsonantTable_Inner_Data[30], 1},
    {&kConsonantTable_Inner_Data[31], 1},
    {&kConsonantTable_Inner_Data[32], 1},
    {&kConsonantTable_Inner_Data[33], 1},
    {&kConsonantTable_Inner_Data[34], 1},
    {&kConsonantTable_Inner_Data[35], 1},
    {&kConsonantTable_Inner_Data[36], 1},
    {&kConsonantTable_Inner_Data[37], 1},
    {&kConsonantTable_Inner_Data[38], 1},
    {&kConsonantTable_Inner_Data[39], 1},
    {&kConsonantTable_Inner_Data[40], 1},
    {&kConsonantTable_Inner_Data[41], 1},
    {&kConsonantTable_Inner_Data[42], 1},
    {&kConsonantTable_Inner_Data[43], 1}
};
constexpr FlatVec<FlatVec<std::uint16_t>> kConsonantTable = { &kConsonantTable_Inner[0], 33 };

constexpr std::uint16_t kEndConsonantTable_Inner_Data[] = { 0x54, 0x50, 0x43, 0x4E, 0x4D, 0x47|kEndConsonantMask, 0x4B|kEndConsonantMask, 0x48|kEndConsonantMask, 0x43, 0x48, 0x4E, 0x48, 0x4E, 0x47 };
constexpr FlatVec<std::uint16_t> kEndConsonantTable_Inner[] = {
    {&kEndConsonantTable_Inner_Data[0], 1},
    {&kEndConsonantTable_Inner_Data[1], 1},
    {&kEndConsonantTable_Inner_Data[2], 1},
    {&kEndConsonantTable_Inner_Data[3], 1},
    {&kEndConsonantTable_Inner_Data[4], 1},
    {&kEndConsonantTable_Inner_Data[5], 1},
    {&kEndConsonantTable_Inner_Data[6], 1},
    {&kEndConsonantTable_Inner_Data[7], 1},
    {&kEndConsonantTable_Inner_Data[8], 2},
    {&kEndConsonantTable_Inner_Data[10], 2},
    {&kEndConsonantTable_Inner_Data[12], 2}
};
constexpr FlatVec<FlatVec<std::uint16_t>> kEndConsonantTable = { &kEndConsonantTable_Inner[0], 11 };

constexpr std::uint16_t kStandaloneWBad_Data[] = { 0x57, 0x45, 0x59, 0x46, 0x4A, 0x4B, 0x5A };
constexpr FlatVec<std::uint16_t> kStandaloneWBad = { &kStandaloneWBad_Data[0], 7 };

constexpr std::uint16_t kDoubleWAllowed_Inner_Data[] = { 0x54, 0x52, 0x54, 0x48, 0x43, 0x48, 0x4E, 0x48, 0x4E, 0x47, 0x4B, 0x48, 0x47, 0x49, 0x50, 0x48, 0x47, 0x48 };
constexpr FlatVec<std::uint16_t> kDoubleWAllowed_Inner[] = {
    {&kDoubleWAllowed_Inner_Data[0], 2},
    {&kDoubleWAllowed_Inner_Data[2], 2},
    {&kDoubleWAllowed_Inner_Data[4], 2},
    {&kDoubleWAllowed_Inner_Data[6], 2},
    {&kDoubleWAllowed_Inner_Data[8], 2},
    {&kDoubleWAllowed_Inner_Data[10], 2},
    {&kDoubleWAllowed_Inner_Data[12], 2},
    {&kDoubleWAllowed_Inner_Data[14], 2},
    {&kDoubleWAllowed_Inner_Data[16], 2}
};
constexpr FlatVec<FlatVec<std::uint16_t>> kDoubleWAllowed = { &kDoubleWAllowed_Inner[0], 9 };

// ---- quick-telex maps ------------------------------------------------
constexpr std::uint16_t kQuickStartConsonant_Data[] = { 0x50, 0x48, 0x47, 0x49, 0x51, 0x55 };
constexpr FlatVec<std::uint16_t> kQuickStartConsonant_Inner[] = { {&kQuickStartConsonant_Data[0], 2}, {&kQuickStartConsonant_Data[2], 2}, {&kQuickStartConsonant_Data[4], 2} };
constexpr FlatMap<std::uint16_t, FlatVec<std::uint16_t>, 3> kQuickStartConsonant = {
    { { 0x46, kQuickStartConsonant_Inner[0] },
    { 0x4A, kQuickStartConsonant_Inner[1] },
    { 0x57, kQuickStartConsonant_Inner[2] } }
};

constexpr std::uint16_t kQuickEndConsonant_Data[] = { 0x4E, 0x47, 0x4E, 0x48, 0x43, 0x48 };
constexpr FlatVec<std::uint16_t> kQuickEndConsonant_Inner[] = { {&kQuickEndConsonant_Data[0], 2}, {&kQuickEndConsonant_Data[2], 2}, {&kQuickEndConsonant_Data[4], 2} };
constexpr FlatMap<std::uint16_t, FlatVec<std::uint16_t>, 3> kQuickEndConsonant = {
    { { 0x47, kQuickEndConsonant_Inner[0] },
    { 0x48, kQuickEndConsonant_Inner[1] },
    { 0x4B, kQuickEndConsonant_Inner[2] } }
};

constexpr std::uint16_t kQuickTelex_Data[] = { 0x43, 0x48, 0x47, 0x49, 0x4B, 0x48, 0x4E, 0x47, 0x50, 0x48, 0x51, 0x55, 0x54, 0x48, 0x55, 0x55 };
constexpr FlatVec<std::uint16_t> kQuickTelex_Inner[] = { {&kQuickTelex_Data[0], 2}, {&kQuickTelex_Data[2], 2}, {&kQuickTelex_Data[4], 2}, {&kQuickTelex_Data[6], 2}, {&kQuickTelex_Data[8], 2}, {&kQuickTelex_Data[10], 2}, {&kQuickTelex_Data[12], 2}, {&kQuickTelex_Data[14], 2} };
constexpr FlatMap<std::uint16_t, FlatVec<std::uint16_t>, 8> kQuickTelex = {
    { { 0x43, kQuickTelex_Inner[0] },
    { 0x47, kQuickTelex_Inner[1] },
    { 0x4B, kQuickTelex_Inner[2] },
    { 0x4E, kQuickTelex_Inner[3] },
    { 0x50, kQuickTelex_Inner[4] },
    { 0x51, kQuickTelex_Inner[5] },
    { 0x54, kQuickTelex_Inner[6] },
    { 0x55, kQuickTelex_Inner[7] } }
};

// ---- codeTableFor -----------------------------------------------------
[[nodiscard]] inline const FlatCodeTable& codeTableFor(int codeTable) noexcept {
    static constexpr std::array<const FlatCodeTable*, 5> tables = {
        &kCodeTableUnicode, &kCodeTableTcvn3, &kCodeTableVniWindows,
        &kCodeTableUnicodeCompound, &kCodeTableCp1258,
    };
    const int idx = (codeTable < 0) ? 0 : (codeTable > 4 ? 4 : codeTable);
    return *tables[static_cast<std::size_t>(idx)];
}

} // namespace ok::text
