#!/usr/bin/env bash
#-----------------------------------------------------------------------------
# KieeKey — regenerate SHA256SUMS.txt
#
# Emits a sha256sum-compatible integrity manifest for the RELEASE TREE, i.e.
# every file tracked by git except the manifest itself (a manifest cannot
# contain its own digest — it would have to be written before it is known).
#
# Why this script exists: SHA256SUMS.txt used to be generated by hand, so it
# silently went stale on the first edit after a release. Run it as the LAST
# step before tagging:
#
#     ./tools/make_sha256sums.sh && git add SHA256SUMS.txt
#
# Verify a download with:   sha256sum -c SHA256SUMS.txt
#-----------------------------------------------------------------------------
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# `KieeKey/` is the name of the directory inside the published release
# archive, so the manifest must use the same prefix a verifier will see.
prefix="$(basename "$PWD")"

{
    git ls-files -z |
    while IFS= read -r -d '' f; do
        [ "$f" = "SHA256SUMS.txt" ] && continue
        # Anchor on the digest + the two-space separator, so a filename that
        # itself contains spaces is prefixed exactly once and not mangled.
        # (sed program in single quotes: no shell backslash escaping needed.)
        sha256sum -- "$f" | sed 's|^\([0-9a-f]\{64\}\)  |\1  PREFIXPLACEHOLDER/|' | sed "s|PREFIXPLACEHOLDER|${prefix}|"
    done
} | LC_ALL=C sort -k 2 > SHA256SUMS.txt

printf 'wrote %s (%s entries)\n' "SHA256SUMS.txt" "$(wc -l < SHA256SUMS.txt)"
